function isCyclic = check_cyclicity(G)
    % Checks if the code generated by G is cyclic (right cyclic shift)
    % G is k x n; rows = generators, columns = codeword positions
    [k, n] = size(G);
    
    % Generate all codewords
    numWords = 2^k;
    codewords = zeros(numWords, n);
    for idx = 0:numWords-1
        v = de2bi(idx, k, 'left-msb')';    % Binary vector of length k
        codewords(idx+1, :) = mod(v' * G, 2); % Generate codeword
    end

    % Check right cyclicity for all codewords
    isCyclic = true;
    for i = 1:numWords
        cw = codewords(i, :);
        cw_shift = [cw(end), cw(1:end-1)];    % Right cyclic shift
        % Check if shifted codeword is in codewords
        found = false;
        for j = 1:numWords
            if isequal(cw_shift, codewords(j, :))
                found = true;
                break;
            end
        end
        if ~found
            isCyclic = false;
            return;
        end
    end
end
